// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EMFindById(arg1) {
  return window['go']['main']['App']['EMFindById'](arg1);
}

export function EMFindManyByWord(arg1) {
  return window['go']['main']['App']['EMFindManyByWord'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
