// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function EMFindById(arg1:number):Promise<models.EMDictionary>;

export function EMFindManyByWord(arg1:string):Promise<models.EMDictionary>;

export function Greet(arg1:string):Promise<string>;
